### ISSUE TITLE
How to use Candlestick?

### ISSUE THREAD

**Issue by PaoloConte** [Kotlin/kandy#149]
Hello,
I can't find any documentation on how to use the candlestick chart type. 
Thanks

**Comment by devcrocod** [comment]
Hello,
Currently, we don't have support for the candlestick chart type in our library. However, I want to let you know that it's definitely on our radar, and we have plans to add it in the near future in `kandy-echarts`: #153

**Comment by PaoloConte** [comment]
Thank you, looking forward to it 😀

**Comment by devcrocod** [comment]
@AndreiKingsley 
What's with the candlestick in `kandy-lets-plot`?

**Comment by AndreiKingsley** [comment]
Waiting for this fix 
https://github.com/JetBrains/lets-plot-kotlin/issues/189
