### ISSUE TITLE
Investigate the possibility of creating and reusing plots and plot settings

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kandy#172]
Explore the feasibility of creating and reusing plots and their settings within the Kandy library. 

* Make an example of that feature
* Documenting this feature 

Part of #85

**Comment by AndreiKingsley** [comment]
Why is this closed? I consider adding a function that allows to add new layers and override layout for existing plot.

**Comment by devcrocod** [comment]
There is a link to the original issue in the description - #85
