### ISSUE TITLE
scale for abLine

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kandy#235]
## **To Reproduce**
```kts
        val dataFrame = mapOf<String, List<Any>>(
            "time" to listOf(1, 2, 3, 4, 5),
            "type" to listOf("A", "A", "B", "B", "C")
        )
        plot(dataFrame) {
            abLine {
                intercept("time)
                slope.constant(0.5)
                width = 2.5
                color("type")
                alpha = 0.7
            }
        }.save("abLineTest.png")
```

or

```kts
       
      plot(dataFrame) {
            abLine {
                intercept.constant(10)
                slope.constant(0.5)
                width = 2.5
                alpha = 0.7
            }
        }.save("abLineTest.png")
```

## **Screenshots**
for 1:
![abLineTest](https://github.com/Kotlin/kandy/assets/19648120/a8dc9f5c-e4ff-4341-9ba3-1d6323e8aedf)

for 2:
![abLineTest](https://github.com/Kotlin/kandy/assets/19648120/e9e74476-b242-47d5-8fc5-df5c11636035)

**Comment by AndreiKingsley** [comment]
This is a bug of lets-plot; Axis scales are not defined automatically - you have to set them manually.

**Comment by AndreiKingsley** [comment]
https://github.com/JetBrains/lets-plot-kotlin/issues/218

**Comment by devcrocod** [comment]
Expected behavior according to https://ggplot2.tidyverse.org/reference/geom_abline.html#details
