### ISSUE TITLE
jvm crashes with sigerr or sigill when trying to save plots in png

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kandy#263]
After updating macos and jdk, my jvm crashes with a fatal error when trying to save plots in PNG or TIFF formats

## **Library Version, Tool version, and Environment**
 - Library version: 0.5.0
 - jdk: openjdk 11.0.21
 - kotlin: 1.9.20
 - macos: 14.1.2 (23B92)

[hs_err_pid25536.log](https://github.com/Kotlin/kandy/files/13603497/hs_err_pid25536.log)

**Comment by devcrocod** [comment]
Check it with lets-plot

**Comment by AndreiKingsley** [comment]
Can't reproduce, please test it with letsPlot:
```
ggsave("plot.png", letsPlot() + geomPoint { x = listOf(1, 2, 3); y = listOf(1, 2, 3) })
```

 If it happens again, report it to [Lets-Plot issues](https://github.com/JetBrains/lets-plot-kotlin/issues) directly

**Comment by devcrocod** [comment]
Can't reproduce

- jdk: openjdk 11.0.21
- kotlin: 1.9.10/1.9.23
- macos: Sonoma 14.4.1
