### ISSUE TITLE
plot saved via `export plot as...` doesn't apply theme

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kandy#265]
If you save the chart through the interface in idea, then the plot will be saved with the default light theme.

## **To Reproduce**
1. choose dark theme in IDEA
2. create a plot 
3. `export plot as...`

## **Expected behavior**
![plot](https://github.com/Kotlin/kandy/assets/19648120/15232581-f34d-4d85-afe0-6824f298f85a)

## **Actual Behavior**
![plot](https://github.com/Kotlin/kandy/assets/19648120/0f6cea48-2124-4ee9-8d04-57c9e0a1375b)

## **Library Version, Tool version, and Environment**
(please complete the following information):
 - Library version: 0.5.0
 - Kotlin-Notebook version: 241.5102

**Comment by AndreiKingsley** [comment]
Are you sure this behavior is expected?

**Comment by AndreiKingsley** [comment]
For me, if I want to use exported plot in some way, I prefer to do it in standard (light) theme.

**Comment by devcrocod** [comment]
> For me, if I want to use exported plot in some way, I prefer to do it in standard (light) theme.

Yes, I expect that exactly the image that I see in the output will be saved

**Comment by AndreiKingsley** [comment]
https://youtrack.jetbrains.com/issue/KTNB-414/Add-UI-export-for-images-and-diagrams-to-the-list-of-supported-formats-from-cells-outputs-in-notebooks#focus=Change-27-9070667.0-0
