### ISSUE TITLE
Example for horizontally grouped bar charts

### ISSUE THREAD

**Issue by stijndcl** [Kotlin/kandy#271]
[This page in the documentation](https://kotlin.github.io/kandy/grouped-bars.html) shows how to create grouped bar charts, and [this page](https://kotlin.github.io/kandy/horizontal-bars.html) shows how to create a horizontal bar chart.

However, I can't seem to create a working grouped horizontal bar chart. I hoped changing `bars` to `barsH` and switching the strings passed to `x` and `y` would suffice, but it seems that some more work is required.

Example:
```kt
val days = listOf("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
val coffee = listOf(0.81, 0.78, 0.72, 0.65, 0.73, 0.49, 0.38)
val tea = listOf(0.12, 0.16, 0.21, 0.26, 0.24, 0.22, 0.30)
val soda = listOf(0.07, 0.06, 0.07, 0.09, 0.03, 0.29, 0.32)
val dataset = mapOf(
    "day" to days + days + days,
    "amount" to coffee + tea + soda,
    "drink" to List(7) { "coffee" } + List(7) { "tea" } + List(7) { "soda" }
)

dataset.plot {
    layout.title = "Weekly Beverage Consumption Trends"
    groupBy("drink") {
        barsH {
            y("day")
            x("amount")
            fillColor("drink") {
                scale = categorical(
                    "coffee" to Color.hex("#6F4E37"),
                    "tea" to Color.hex("#C2D4AB"),
                    "soda" to Color.hex("#B5651D")
                )
            }
        }
    }
}
```
![image](https://github.com/Kotlin/kandy/assets/60451863/41505053-6fcd-4343-80ea-9058e95cee1d)

As the above image shows, the bars are drawn over each other instead of nicely grouping vertically.

Is there a way to do this correctly in Kandy? If yes, would it perhaps be possible to add a simple example to the `Grouped Bars` examples page?

**Comment by devcrocod** [comment]
Your code is correct. This will actually draw horizontal bars on the grouped data. See example:

https://datalore.jetbrains.com/report/static/KQKedA4jDrKu63O53gEN0z/l6g5xyLoYVOmk4BC568YYJ

How do you import kandy?

If you are working in a notebook, try the following code:

```
%useLatestDescriptors
%use kandy
```

or specify the version:

```
%use kandy(0.5.0)
```

**Comment by stijndcl** [comment]
I was testing it out in a notebook, indeed. `%useLatestDescriptors` seems to fix it. Thanks!
