### ISSUE TITLE
Tooltips doesn't work with grouped data

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kandy#275]
## **Describe the bug**
I can't call tooltips with formats or title parameters. I got missing arguments exception

## **To Reproduce**
```kotlin
yearDf.groupBy { name }.plot { 
    line {
        x(month)
        y(uniqueD) { axis.name = "Download from Unique IPs"}
        color(name)
        tooltips(title = "blabla") {
            line("downloads", uniqueD.tooltipValue())
        }
     }
     layout.size = 950 to 500
 }
 ```

## **Expected behavior**
Get tooltips with my settings.

## **Actual Behavior**
Got exception

## **Library Version, Tool version, and Environment**
Using datalore

 - Library version: 0.5.0

**Comment by AndreiKingsley** [comment]
Can't reproduce (works on a little dataset, see attached screenshot), please attach your data.
<img width="874" alt="image" src="https://github.com/Kotlin/kandy/assets/49092338/769ea316-e890-4f3f-b5e9-ccb44250849b">

**Comment by devcrocod** [comment]
Can't reproduce

kandy 0.6.0
datalore/idea
