### ISSUE TITLE
Research of geo plotting capabilities

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kandy#280]
Given the broad scope of this area, an initial research phase is crucial before proceeding to actual implementation.

* Data
  - `lets-plot` geo looks like this: https://github.com/JetBrains/lets-plot-kotlin/blob/master/docs/geotools.md
  - Examine Python's implementation with 'geopandas' as a potential model. We can aim to implement something similar in Kotlin, utilizing dataframes and providing the necessary extensions.
  - Determine which geo engine would be the most suitable for our purposes.
* API Design for geo plotting

**Comment by ge0ffrey** [comment]
Once you have something, I'd love to try this out to visualize the result of [our vehicle routing Kotlin notebook](https://github.com/TimefoldAI/timefold-notebooks/blob/main/kotlin/vehicle-routing.ipynb).
