### ISSUE TITLE
Can it be used on Android? Or are there plans for Android compatibility?

### ISSUE THREAD

**Issue by Quyunshuo** [Kotlin/kandy#287]

**Comment by AndreiKingsley** [comment]
Hi. So far we haven't dealt with the operability of kandy on Android. Added issue #289, all related updates will be in it.

**Comment by AndreiKingsley** [comment]
Hi! I added simple Kandy android app with Lets-Plot Skiko frontend:
https://github.com/AndreiKingsley/kandy_android_skiko
However it's experimental and can be unstable.
