### ISSUE TITLE
[BUG] Hower-up duplication in Bar Plot

### ISSUE THREAD

**Issue by teodor-i** [Kotlin/kandy#290]
It's currently duplicating hower-up windows until you move the cursor out of the plot border.

IDEA:
IntelliJ IDEA 2023.3 RC (Ultimate Edition)
Build #IU-233.11799.196, built on November 29, 2023
![random_data](https://github.com/Kotlin/kandy/assets/14848811/180ba60d-a5e2-4495-8721-deaf3e750927)

**Comment by AndreiKingsley** [comment]
It's a known problem. Waiting for this fix https://github.com/JetBrains/lets-plot-kotlin/issues/225

**Comment by devcrocod** [comment]
Check it
