### ISSUE TITLE
Add new scales transformations

### ISSUE THREAD

**Issue by AndreiKingsley** [Kotlin/kandy#311]
`log2` and `logsym`
https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.5.0/new_scale_transformations.ipynb

**Comment by devcrocod** [comment]
We already have transformations in scales
What do you mean by "new scales transformations"?

**Comment by AndreiKingsley** [comment]
There are some new ones:
https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.5.0/new_scale_transformations.ipynb
