### ISSUE TITLE
Add export to SVG and PNG as `ByteArray`

### ISSUE THREAD

**Issue by AndreiKingsley** [Kotlin/kandy#325]
Add `.toPNG(): ByteArray` and `.toJPG(): ByteArray` extensions for plot/grid/bunch (all logic is almost aldready written in `.toBufferedImage()`)

**Comment by gulshanpatidar** [comment]
Hi @AndreiKingsley. 
I raised [this](https://github.com/Kotlin/kandy/pull/340) pr for it.
please have a loot at it.
