### ISSUE TITLE
[BUG] After rendeing a plot I can not save it

### ISSUE THREAD

**Issue by holloszaboakos** [Kotlin/kandy#351]
## **Describe the bug**
According to tutorials there supposed to be a save as option in the output top right ... menu, when a plot is displayed in the output.
In my menu there is no such option and I did not find a method to save the plot programatically.

## **To Reproduce**
I use the newest available version of InettIJ, kotlin notebook, and the kandy version it automatically imports by 
%use kandy
%use dataframe

When I generate any plot I check the output menu.
There are only two options!

## **Screenshots**
![image](https://github.com/Kotlin/kandy/assets/23530572/90bd511d-0722-40ee-adde-a079bbba5071)

Here everithing is red, becouse I did not run the notebook to create the picture.
But its the same after running.

## **Library Version, Tool version, and Environment**
 - Kotlin-Notebook version: 233.14475.9

**Comment by AndreiKingsley** [comment]
Hi, it will be possible to save a Kandy plot from a Kotlin Notebook output starting with version 241. Please, use `Plot.save()` for now.

**Comment by AndreiKingsley** [comment]
@holloszaboakos hi! IDEA 2024.1 has been released and since this vetsion plot export from the cell should be available in Kotlin Notebook.

**Comment by holloszaboakos** [comment]
> @holloszaboakos hi! IDEA 2024.1 has been released and since this version plot export from the cell should be available in Kotlin Notebook.

Fantastic news! :) It works perfectly.
