### ISSUE TITLE
Add table of contents to Quick Start Guide

### ISSUE THREAD

**Issue by AndreiKingsley** [Kotlin/kandy#365]
Quick start guide has TOC in notebooks, but not in the documentation.

**Comment by devcrocod** [comment]
This is not true:
<img width="1728" alt="Screenshot 2024-04-02 at 18 20 05" src="https://github.com/Kotlin/kandy/assets/19648120/cd3f2195-bb50-4f87-bd98-4fcfdf2cc900">

**Comment by AndreiKingsley** [comment]
Ok, for some reason it didn't seem like TOC in my head.
