### ISSUE TITLE
Follow official doc. Cannot setup "Plugin" and "import" in IntelliJ IDEA environment !

### ISSUE THREAD

**Issue by nuclear718** [Kotlin/kandy#373]
I am a beginner in Kotlin, and I have encountered an issue while using Kandy in the IntelliJ IDEA environment. Following the instructions, I have added the following line to the dependencies section in my Gradle file:

`implementation 'org.jetbrains.kotlinx:kandy-lets-plot:0.6.0'`

However, when I return to the Kotlin code editor, I cannot successfully import:

`import org.jetbrains.kotlinx.kandy.dsl.plot`

This is extremely frustrating, as there is no documentation guiding beginners like myself on how to configure the necessary plugins in Gradle. With only the dependencies set up and no plugins, I cannot achieve any auto-completion or auto-import functionality for the ".plot" or any other Kandy-related packages. Even manually copying and pasting the line:

`import org.jetbrains.kotlinx.kandy.dsl.plot`

results in 'kandy' being underlined in red, indicating that IntelliJ IDEA does not recognize how to import Kandy...

Please, as beginners, we urgently need detailed usage instructions...

**Comment by devcrocod** [comment]
If you're a beginner in Kotlin, then, initially, you should learn the language and the gradle build system. The documentation of a library (any library) doesn't cover the basics of the language or build systems. Btw, Kandy doesn't have a Gradle plugin or any other plugin as artefact.

You can use the [official documentation of Kotlin](https://kotlinlang.org/docs/home.html) and [Gradle](https://docs.gradle.org/current/userguide/userguide.html). They are quite detailed and cover everything necessary. There are also plenty of training courses for beginners, like example: [academy](https://academy.jetbrains.com/?tag=Kotlin&_gl=1*1dhtxba*_ga*Njk1MjUzMjI0LjE2ODg3MzIyNjk.*_ga_9J976DJZ68*MTcxMjIzMTg0Mi4xNzMuMC4xNzEyMjMxODQyLjYwLjAuMA..&_ga=2.256114761.378915170.1712231842-695253224.1688732269), [from meta](https://www.coursera.org/learn/meta-programming-fundamentals-kotlin), [from google](https://developer.android.com/courses/pathways/android-basics-compose-unit-1-pathway-1)

**Comment by devcrocod** [comment]
Regarding your issue, place the Kandy dependency in the dependencies section of your gradle build script:
```
dependencies {
    implementation("org.jetbrains.kotlinx:kandy-lets-plot:0.6.0")
}
```

After that, update gradle to download the new artifact

**Comment by nuclear718** [comment]
> Regarding your issue, place the Kandy dependency in the dependencies section of your gradle build script:
> 
> ```
> dependencies {
>     implementation("org.jetbrains.kotlinx:kandy-lets-plot:0.6.0")
> }
> ```
> 
> After that, update gradle to download the new artifact

Of course, I did it and the gradle run it well but that does not work in IntelliJ IDEA. 

After I finished adding dependencies in Gradle, Gradle ran it well without any error messages.

However, when I went back to the code editor, I was unable to complete the import automatically or manually.

**Comment by nuclear718** [comment]
> Regarding your issue, place the Kandy dependency in the dependencies section of your gradle build script:
> 
> ```
> dependencies {
>     implementation("org.jetbrains.kotlinx:kandy-lets-plot:0.6.0")
> }
> ```
> 
> After that, update gradle to download the new artifact



> dependencies

In other packages like dataframe, everything worked perfectly fine. I completely followed their official documentation and set up the dependencies and plugins step-by-step in Gradle without any obstructions. I was able to complete the setup, and the imports were done automatically in my program, and it worked well. The approach given in their official documentation worked.  Being the same beginner, following different official documentation yielded completely contrasting results.

**Comment by devcrocod** [comment]
> The issue I want to reflect on is quite simple. When I followed the official documentation step-by-step, I was unable to complete even the most basic example as described in the documentation. Do you think this is a beginner's issue, or should the documentation provide more comprehensive explanations? I believe this is a minor issue with the project, and this issue should not be closed until it is resolved!

Once again, how do you see a solution to this problem? Specifying the dependency is all that is required to add the library. You can verify this if you look at maven central where dependencies are also specified:

https://central.sonatype.com/artifact/org.jetbrains.kotlinx/kandy-lets-plot
https://central.sonatype.com/artifact/org.jetbrains.kotlinx/dataframe/0.14.0-dev-2985

**Comment by nuclear718** [comment]
> > The issue I want to reflect on is quite simple. When I followed the official documentation step-by-step, I was unable to complete even the most basic example as described in the documentation. Do you think this is a beginner's issue, or should the documentation provide more comprehensive explanations? I believe this is a minor issue with the project, and this issue should not be closed until it is resolved!
> 
> Once again, how do you see a solution to this problem? Specifying the dependency is all that is required to add the library. You can verify this if you look at maven central where dependencies are also specified:
> 
> https://central.sonatype.com/artifact/org.jetbrains.kotlinx/kandy-lets-plot https://central.sonatype.com/artifact/org.jetbrains.kotlinx/dataframe/0.14.0-dev-2985


Once again, what I'm trying to say is very simple: Why is it that by following the official documentation, I am unable to implement even the simplest example?
The problem is that the official documentation is not comprehensive enough! If it could be more thorough, it would be more newcomer-friendly for those entering this field.

Issue #374 highlights this problem too.

**Comment by devcrocod** [comment]
What does complete documentation mean? We can make it more detailed, but what should it look like?

If you need to specify a dependency to download a dependency, that is what is in the documentation.

In Kandy, there are no plugins, no special conditions for adding to Android, and Kandy artifacts are located in Maven Central - so specifying a dependency is essentially the full documentation for add library with gradle.

If we have missed something specific or we made a mistake, as you found in #374, or if you have a specific suggestion on how to improve this area, we would be happy to do so. Since none of this was in the issue, that's why I closed it.

We have issues concerning documentation improvements, you can find them by the `documentation` tag and 👍 if it concerns you. If you don't find a suitable issue, you can create your own where you describe a specific suggestion for improvement.
