### ISSUE TITLE
Fix links in docs

### ISSUE THREAD

**Issue by AndreiKingsley** [Kotlin/kandy#383]
GitHub notebook link is invalid here:
https://kotlin.github.io/kandy/density-plot-with-histogram.html

**Comment by devcrocod** [comment]
Github notebook links:
- https://kotlin.github.io/kandy/ribbon-with-line.html
- https://kotlin.github.io/kandy/several-ribbons.html
- https://kotlin.github.io/kandy/density-plot-with-histogram.html
- https://kotlin.github.io/kandy/candlestick-settings-dsl.html
- https://kotlin.github.io/kandy/candlestick-settings-stat-api.html
