### ISSUE TITLE
Add "positional categorical: functions with `vararg` (instead of list of categories)

### ISSUE THREAD

**Issue by AndreiKingsley** [Kotlin/kandy#426]
Add an analogue for all existing functions that create positional scales with `vararg` of categories instead of list of categories.

* `PositionalMappingParameters<*>.categorical()`
* `Scale.Companion.categoricalPos`

https://github.com/Kotlin/kandy/blob/main/kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/scale.kt

**Comment by lucas-watkins** [comment]
Hello, is this issue still available?

**Comment by AndreiKingsley** [comment]
@lucas-watkins hello! Yes.

**Comment by lucas-watkins** [comment]
May I submit a PR? All the tests are passing locally and I've added 2 new tests that deal with varargs specifically.

**Comment by AndreiKingsley** [comment]
Yeah, sure!
